# Generated by Django 5.1.7 on 2025-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Wycieczka',
                'verbose_name_plural': 'Wycieczki',
                'db_table': 'itineraries',
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nazwa', max_length=255, verbose_name='Nazwa')),
                ('description', models.TextField(help_text='Opis', max_length=5120, verbose_name='Opis')),
                ('location', models.CharField(help_text='Lokacja', max_length=255, verbose_name='Lokacja')),
                ('date', models.DateField(help_text='data aktywności', verbose_name='data')),
                ('start_time', models.TimeField(help_text='Czas rozpoczęcia', verbose_name='Czas zakończenia')),
                ('duration', models.IntegerField(help_text='Czas trawania', verbose_name='Czas trwania')),
            ],
            options={
                'verbose_name': 'Aktywność',
                'verbose_name_plural': 'Aktywności',
                'db_table': 'itinerary_activities',
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nazwa', max_length=124, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Typ aktywności planu',
                'verbose_name_plural': 'Typy aktywności planu',
            },
        ),
    ]
