# Generated by Django 5.1.7 on 2025-05-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa", max_length=124, verbose_name="Nazwa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ aktywności planu",
                "verbose_name_plural": "Typy aktywności planu",
            },
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wycieczka",
                "verbose_name_plural": "Wycieczki",
                "db_table": "itineraries",
            },
        ),
        migrations.CreateModel(
            name="ItineraryActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa", max_length=255, verbose_name="Nazwa"
                    ),
                ),
                (
                    "ticket",
                    models.FileField(blank=True, null=True, upload_to="itineraries/"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Opis",
                        max_length=5120,
                        null=True,
                        verbose_name="Opis",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Lokacja",
                        max_length=255,
                        null=True,
                        verbose_name="Lokacja",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="data aktywności", verbose_name="data"),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Czas rozpoczęcia",
                        null=True,
                        verbose_name="Czas zakończenia",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        help_text="Czas trawania",
                        null=True,
                        verbose_name="Czas trwania",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        help_text="Plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="itineraries.itinerary",
                        verbose_name="Plan",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Typ",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itineraries.itineraryactivitytype",
                        verbose_name="Typ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktywność",
                "verbose_name_plural": "Aktywności",
                "db_table": "itinerary_activities",
            },
        ),
    ]
