# Generated by Django 5.1.5 on 2025-03-21 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0001_initial"),
        ("trips", "0002_alter_budget_options_alter_expensetype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itineraries",
                to="trips.trip",
            ),
        ),
    ]
