# Generated by Django 5.1.7 on 2025-04-15 11:17

import django.db.models.deletion
import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nazwa', max_length=124, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Typ aktywności planu',
                'verbose_name_plural': 'Typy aktywności planu',
            },
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='description',
            field=models.TextField(help_text='Opis', max_length=5120, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='duration',
            field=models.IntegerField(help_text='Czas trawania', verbose_name='Czas trwania'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='itinerary',
            field=models.ForeignKey(help_text='Plan', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itineraries.itinerary', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='location',
            field=models.CharField(help_text='Lokacja', max_length=255, verbose_name='Lokacja'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='name',
            field=models.CharField(help_text='Nazwa', max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='start_time',
            field=models.TimeField(help_text='Czas rozpoczęcia', verbose_name='Czas zakończenia'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='type',
            field=models.ForeignKey(default=itineraries.models.get_default_itinerary_activity_type, help_text='Typ', on_delete=django.db.models.deletion.CASCADE, to='itineraries.itineraryactivitytype', verbose_name='Typ'),
        ),
    ]
