# Generated by Django 5.1.7 on 2025-04-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='itinerary',
            field=models.ForeignKey(help_text='Plan', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itineraries.itinerary', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='type',
            field=models.ForeignKey(help_text='Typ', on_delete=django.db.models.deletion.CASCADE, to='itineraries.itineraryactivitytype', verbose_name='Typ'),
        ),
    ]
