# Generated by Django 5.1.7 on 2025-05-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryactivity',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trips.ticket'),
        ),
    ]
