# Generated by Django 5.1.5 on 2025-01-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryactivity',
            name='type',
            field=models.CharField(choices=[('test1', 'test1'), ('test2', 'test2'), ('test3', 'test3')], max_length=255),
        ),
    ]
