# Generated by Django 5.1.7 on 2025-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryactivity',
            name='description',
            field=models.TextField(help_text='Opis', max_length=5120, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='duration',
            field=models.IntegerField(help_text='Czas trawania', null=True, verbose_name='Czas trwania'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='location',
            field=models.CharField(help_text='Lokacja', max_length=255, null=True, verbose_name='Lokacja'),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='start_time',
            field=models.TimeField(help_text='Czas rozpoczęcia', null=True, verbose_name='Czas zakończenia'),
        ),
    ]
