# Generated by Django 5.1.7 on 2025-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryactivity',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='itineraries/'),
        ),
    ]
