# Generated by Django 5.1.7 on 2025-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0002_itineraryactivitytype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryactivity",
            name="date",
            field=models.DateField(
                default="2025-04-22", help_text="data aktywności", verbose_name="data"
            ),
            preserve_default=False,
        ),
    ]
