# Generated by Django 5.1.7 on 2025-05-31 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_alter_itineraryactivity_ticket'),
        ('trips', '0009_alter_ticket_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryactivity',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.ticket'),
        ),
    ]
