# Generated by Django 5.1.7 on 2025-03-26 16:26

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Kod uprawnienia', max_length=128, unique=True, verbose_name='Kod uprawnienia')),
                ('can_view', models.BooleanField(default=False, help_text='Czy ma dostęp do READ', verbose_name='Czy ma dostęp do READ')),
                ('can_edit', models.BooleanField(default=False, help_text='Czy ma dostęp do WRITE', verbose_name='Czy ma dostęp do WRITE')),
                ('can_delete', models.BooleanField(default=False, help_text='Czy ma dostęp do DELETE', verbose_name='Czy ma dostęp do DELETE')),
                ('is_active', models.BooleanField(default=True, help_text='Czy aktywne', verbose_name='Czy aktywne')),
            ],
            options={
                'verbose_name': 'Uprawnienie',
                'verbose_name_plural': 'Uprawnienia',
                'db_table': 'permissions',
                'ordering': ['-created_at'],
                'get_latest_by': '-created_at',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
