# Generated by Django 5.1.7 on 2025-05-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("str", "String"),
                            ("bool", "Boolean"),
                            ("json", "JSON"),
                        ],
                        max_length=50,
                    ),
                ),
                ("int_value", models.IntegerField(blank=True, null=True)),
                ("float_value", models.FloatField(blank=True, null=True)),
                ("str_value", models.CharField(blank=True, max_length=255, null=True)),
                ("bool_value", models.BooleanField(default=False)),
                ("json_value", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "System Variable",
                "verbose_name_plural": "System Variables",
            },
        ),
    ]
