# Generated by Django 5.1.7 on 2025-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nazwa', max_length=50, verbose_name='Nazwa')),
                ('type', models.CharField(choices=[('private', 'Prywatny'), ('group', 'Grupowy')], default='private', help_text='Typ', max_length=32, verbose_name='Typ')),
                ('settings', models.JSONField(default=dict, help_text='Ustawienia', verbose_name='Ustawienia')),
            ],
            options={
                'verbose_name': 'Pokój do czatowania',
                'verbose_name_plural': 'Pokoje do czatowania',
                'db_table': 'chat_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Nazwa', max_length=512, verbose_name='Nazwa')),
                ('file', models.FileField(blank=True, help_text='Plik', null=True, upload_to='chat_files/', verbose_name='Plik')),
            ],
            options={
                'verbose_name': 'Wiadomość czatu',
                'verbose_name_plural': 'Wiadomości czatu',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
