# Generated by Django 5.1.5 on 2025-01-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nazwa', max_length=50, verbose_name='Nazwa')),
                ('type', models.CharField(choices=[('private', 'Prywatny'), ('group', 'Grupowy')], default='private', help_text='Typ', max_length=32, verbose_name='Typ')),
                ('settings', models.JSONField(default=dict, help_text='Ustawienia', verbose_name='Ustawienia')),
                ('creator', models.ForeignKey(help_text='Przewodnik', on_delete=django.db.models.deletion.PROTECT, related_name='chat_rooms_creator', to='users.userprofile', verbose_name='Przewodnik')),
                ('members', models.ManyToManyField(blank=True, help_text='Turyści', related_name='chat_rooms', to='users.userprofile', verbose_name='Turysta')),
                ('trip', models.ForeignKey(help_text='Wycieczka', on_delete=django.db.models.deletion.PROTECT, related_name='chat_rooms', to='trips.trip', verbose_name='Wycieczka')),
            ],
            options={
                'verbose_name': 'Pokój do czatowania',
                'verbose_name_plural': 'Pokoje do czatowania',
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='Nazwa', max_length=512, verbose_name='Nazwa')),
                ('file', models.FileField(blank=True, help_text='Plik', null=True, upload_to='chat_files/', verbose_name='Plik')),
                ('profile', models.ForeignKey(help_text='Autor wiadomości', on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to='users.userprofile', verbose_name='Autor wiadomości')),
                ('chatroom', models.ForeignKey(help_text='Pokój do czatowania', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chatroom', verbose_name='Pokój do czatowania')),
            ],
            options={
                'verbose_name': 'Wiadomość czatu',
                'verbose_name_plural': 'Wiadomości czatu',
                'db_table': 'chat_messages',
            },
        ),
    ]
