# Generated by Django 5.1.7 on 2025-04-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0002_userprofiletype_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(help_text='Przewodnik', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_creator', to='users.userprofile', verbose_name='Przewodnik'),
        ),
    ]
