# Generated by Django 5.1.7 on 2025-04-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(help_text='Przewodnik', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_creator', to='users.userprofile', verbose_name='Przewodnik'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Turyści', related_name='chat_rooms', to='users.userprofile', verbose_name='Turysta'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='trip',
            field=models.ForeignKey(help_text='Wycieczka', on_delete=django.db.models.deletion.PROTECT, related_name='chat_rooms', to='trips.trip', verbose_name='Wycieczka'),
        ),
        migrations.AddField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(help_text='Pokój do czatowania', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatroom', verbose_name='Pokój do czatowania'),
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(help_text='Autor wiadomości', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='users.userprofile', verbose_name='Autor wiadomości'),
        ),
    ]
