# Generated by Django 5.1.7 on 2025-05-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='trip',
            field=models.ForeignKey(help_text='Wycieczka', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='trips.trip', verbose_name='Wycieczka'),
        ),
    ]
