# Generated by Django 5.1.5 on 2025-03-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Wiadomość czatu",
                "verbose_name_plural": "Wiadomości czatu",
            },
        ),
        migrations.AlterModelOptions(
            name="chatroom",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pokój do czatowania",
                "verbose_name_plural": "Pokoje do czatowania",
            },
        ),
    ]
