# Generated by Django 5.1.7 on 2025-05-24 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatroom_trip'),
        ('users', '0003_userprofile_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(help_text='Autor wiadomości', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.userprofile', verbose_name='Autor wiadomości'),
        ),
    ]
