# Generated by Django 5.1.7 on 2025-04-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatroom_creator'),
        ('users', '0003_alter_userprofile_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Nazwa', max_length=512, verbose_name='Nazwa')),
                ('file', models.FileField(blank=True, help_text='Plik', null=True, upload_to='chat_files/', verbose_name='Plik')),
                ('chatroom', models.ForeignKey(help_text='Pokój do czatowania', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatroom', verbose_name='Pokój do czatowania')),
                ('profile', models.ForeignKey(help_text='Autor wiadomości', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='users.userprofile', verbose_name='Autor wiadomości')),
            ],
            options={
                'verbose_name': 'Wiadomość czatu',
                'verbose_name_plural': 'Wiadomości czatu',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
