# Generated by Django 5.1.5 on 2025-03-21 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
        ("users", "0002_alter_customuser_options_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"verbose_name": "Budżet", "verbose_name_plural": "Budżety"},
        ),
        migrations.AlterModelOptions(
            name="expensetype",
            options={
                "verbose_name": "Typ wydatku",
                "verbose_name_plural": "Typy wydatków",
            },
        ),
        migrations.AlterModelOptions(
            name="tickettype",
            options={
                "verbose_name": "Typ biletu",
                "verbose_name_plural": "Typy biletów",
            },
        ),
        migrations.AlterField(
            model_name="budget",
            name="trip",
            field=models.OneToOneField(
                help_text="Powiązana wycieczka",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="trips.trip",
                verbose_name="Wycieczka",
            ),
        ),
        migrations.CreateModel(
            name="TripAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        help_text="Token", max_length=24, verbose_name="Token"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="trips.trip",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token dostępu do wycieczki",
                "verbose_name_plural": "Tokeny dostępu do wycieczek",
                "unique_together": {("trip", "user_profile")},
            },
        ),
    ]
