# Generated by Django 5.1.7 on 2025-03-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='settings',
        ),
    ]
