# Generated by Django 5.1.7 on 2025-04-23 12:31

import django.db.models.deletion
import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Osoba, która poniosła wydatek', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.userprofile', verbose_name='Użytkownik'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=trips.models.get_default_expense_type, help_text='Kategoria wydatku', on_delete=django.db.models.deletion.CASCADE, to='trips.expensetype', verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='profile',
            field=models.ForeignKey(help_text='Profil', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.userprofile', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(default=trips.models.get_default_ticket_type, help_text='Typ', on_delete=django.db.models.deletion.CASCADE, to='trips.tickettype', verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(help_text='Właściciel', on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_creator', to='users.userprofile', verbose_name='Właściciel'),
        ),
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Profil', related_name='trips_as_member', to='users.userprofile', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(help_text='Wycieczka', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='trips.trip', verbose_name='Wycieczka'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(help_text='Powiązana podróż', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip', verbose_name='Podróż'),
        ),
        migrations.AddField(
            model_name='budget',
            name='trip',
            field=models.OneToOneField(help_text='Powiązana wycieczka', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='trips.trip', verbose_name='Wycieczka'),
        ),
        migrations.AddField(
            model_name='tripaccesstoken',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripaccesstoken',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_access_tokens', to='users.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='tripaccesstoken',
            unique_together={('trip', 'user_profile')},
        ),
    ]
