# Generated by Django 5.1.5 on 2025-01-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='members',
        ),
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Profil', related_name='trips_as_member', to='users.userprofile', verbose_name='Profil'),
        ),
    ]
