# Generated by Django 5.1.7 on 2025-05-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="budget_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Budżet wycieczki",
                max_digits=10,
                verbose_name="Budżet",
            ),
        ),
    ]
