# Generated by Django 5.1.7 on 2025-04-05 18:39

import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripaccesstoken',
            name='is_pending',
            field=models.BooleanField(default=True, help_text='Czy oczekujący', verbose_name='Czy oczekujący'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(help_text='Kod waluty zgodny z ISO 4217 (np. PLN, EUR, USD)', max_length=3, validators=[trips.models.validate_iso_currency], verbose_name='Waluta'),
        ),
    ]
