# Generated by Django 5.1.5 on 2025-01-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_members_trip_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='budget',
        ),
    ]
