# Generated by Django 5.1.7 on 2025-04-15 11:53

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripaccesstoken_is_pending_alter_budget_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(help_text='Nazwa', max_length=124, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z]+$'), 'Enter a valid alphabetic code')], verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(help_text='Nazwa', max_length=124, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z]+$'), 'Enter a valid alphabetic code')], verbose_name='Nazwa'),
        ),
    ]
