# Generated by Django 5.1.7 on 2025-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='settings',
            field=models.JSONField(default=dict, help_text='Ustawienia', verbose_name='Ustawienia'),
        ),
    ]
