# Generated by Django 5.1.7 on 2025-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Bilet', 'verbose_name_plural': 'Bilety'},
        ),
    ]
