# Generated by Django 5.1.7 on 2025-05-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_budget_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
