# Generated by Django 5.1.7 on 2025-05-13 21:49

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_delete_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(help_text='Nazwa', max_length=124, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]+$'), 'Wprowadź poprawny alfabetystyczny ciąg znaków (bez cyfr i symboli).')], verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(help_text='Nazwa', max_length=124, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]+$'), 'Wprowadź poprawny alfabetystyczny ciąg znaków (bez cyfr i symboli).')], verbose_name='Nazwa'),
        ),
    ]
