# Generated by Django 5.1.5 on 2025-01-30 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_budget'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='activity',
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Kwota budżetu', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kwota budżetu')),
                ('currency', models.CharField(help_text='Waluta (np. USD, PLN)', max_length=10, verbose_name='Waluta')),
                ('trip', models.ForeignKey(help_text='Powiązana wycieczka', on_delete=django.db.models.deletion.CASCADE, related_name='budżet', to='trips.trip', verbose_name='Wycieczka')),
            ],
            options={
                'verbose_name': 'Budżet',
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Kwota wydatku', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kwota wydatku')),
                ('date', models.DateField(help_text='Data wydatku', verbose_name='Data')),
                ('description', models.TextField(blank=True, help_text='Opis wydatku (opcjonalne)', verbose_name='Opis')),
                ('type', models.CharField(choices=[('test1', 'test1'), ('test2', 'test2'), ('test2', 'test2')], default='other', help_text='Rodzaj wydatku', max_length=50, verbose_name='Rodzaj wydatku')),
                ('trip', models.ForeignKey(help_text='Powiązana wycieczka', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip', verbose_name='Wycieczka')),
                ('user', models.ForeignKey(help_text='Osoba, która poniosła wydatek', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.userprofile', verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wydatek',
                'verbose_name_plural': 'Wydatki',
                'db_table': 'expenses',
            },
        ),
        migrations.DeleteModel(
            name='TripActivity',
        ),
    ]
