# Generated by Django 5.1.7 on 2025-04-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_budget_options_alter_expensetype_options_and_more"),
        ("trips", "0002_tripaccesstoken_is_pending_alter_budget_currency"),
        ("trips", "0003_trip_settings"),
    ]

    operations = []
