# Generated by Django 5.1.7 on 2025-04-29 12:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(help_text='Bilet', storage=django.core.files.storage.FileSystemStorage(), upload_to='tickets/', verbose_name='Bilet'),
        ),
    ]
