# Generated by Django 5.1.7 on 2025-04-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_expensetype_name_alter_tickettype_name'),
        ('users', '0004_remove_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripaccesstoken',
            name='token',
            field=models.CharField(help_text='Token', max_length=24, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='tripaccesstoken',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_access_tokens', to='users.userprofile'),
        ),
    ]
