# Generated by Django 5.1.7 on 2025-04-29 13:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(help_text='Bilet', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='tickets/', verbose_name='Bilet'),
        ),
    ]
