# Generated by Django 5.1.7 on 2025-04-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_tripaccesstoken_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='currency',
        ),
    ]
