# Generated by Django 5.1.7 on 2025-05-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_detailedexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedexpense',
            name='trip',
            field=models.ForeignKey(default=1, help_text='Wycieczka', on_delete=django.db.models.deletion.CASCADE, related_name='detailed_expenses', to='trips.trip', verbose_name='Wycieczka'),
            preserve_default=False,
        ),
    ]
