# Generated by Django 5.1.7 on 2025-05-25 14:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_detailedexpense_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedexpense',
            name='price',
        ),
        migrations.RemoveField(
            model_name='detailedexpense',
            name='price_in_pln',
        ),
        migrations.RemoveField(
            model_name='detailedexpense',
            name='price_per_member',
        ),
        migrations.RemoveField(
            model_name='detailedexpense',
            name='price_per_member_in_pln',
        ),
        migrations.AddField(
            model_name='detailedexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='AMOUNT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailedexpense',
            name='amount_in_pln',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AMOUNT IN PLN', max_digits=10, verbose_name='Kwota w PLN'),
        ),
        migrations.AddField(
            model_name='detailedexpense',
            name='amount_per_member',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AMOUNT PER MEMBER', max_digits=10, verbose_name='Kwota na osobę'),
        ),
        migrations.AddField(
            model_name='detailedexpense',
            name='amount_per_member_in_pln',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AMOUNT PER MEMBER IN PLN', max_digits=10, verbose_name='Kwota na osobę w PLN'),
        ),
    ]
