# Generated by Django 5.1.7 on 2025-05-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_detailedexpense_created_at_and_more'),
        ('users', '0004_customuser_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='profiles',
            field=models.ManyToManyField(blank=True, help_text='Profile, które mają dostęp do biletu', null=True, related_name='shared_tickets', to='users.userprofile', verbose_name='Udostępnione profile'),
        ),
    ]
