# Generated by Django 5.1.7 on 2025-04-15 11:53

import django.core.validators
import django.db.models.deletion
import re
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Kod typu profilu', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z]+$'), 'Enter a valid alphabetic code')], verbose_name='Kod')),
                ('name', models.CharField(help_text='Nazwa typu profilu', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z]+$'), 'Enter a valid alphabetic code')], verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Typ profilu użytkownika',
                'verbose_name_plural': 'Typy profili użytkowników',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.ForeignKey(default=users.models.get_default_user_profile_type, help_text='Typ profilu', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='users.userprofiletype', verbose_name='Typ profilu'),
        ),
    ]
