# Generated by Django 5.1.7 on 2025-05-13 21:49

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Imię użytkownika', max_length=32, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]+$'), 'Wprowadź poprawny alfabetystyczny ciąg znaków (bez cyfr i symboli).')], verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Nazwisko użytkownika', max_length=32, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]+$'), 'Wprowadź poprawny alfabetystyczny ciąg znaków (bez cyfr i symboli).')], verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='userprofiletype',
            name='code',
            field=models.CharField(help_text='Kod typu profilu', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]+$'), 'Wprowadź poprawny alfabetystyczny ciąg znaków (bez cyfr i symboli).')], verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='userprofiletype',
            name='name',
            field=models.CharField(help_text='Nazwa typu profilu', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]+$'), 'Wprowadź poprawny alfabetystyczny ciąg znaków (bez cyfr i symboli).')], verbose_name='Nazwa'),
        ),
    ]
