# Generated by Django 5.1.5 on 2025-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Użytkownik",
                "verbose_name_plural": "Użytkownicy",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Profil", "verbose_name_plural": "Profile"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_guest",
            field=models.BooleanField(
                default=False, help_text="Czy konto gościa", verbose_name="Czy gość"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="type",
            field=models.CharField(
                choices=[
                    ("client", "Klient"),
                    ("guide", "Przewodnik"),
                    ("admin", "Administrator"),
                    ("guest", "Gość"),
                ],
                default="client",
                help_text="Typ profilu",
                max_length=32,
                verbose_name="Typ",
            ),
        ),
    ]
