# Generated by Django 5.1.7 on 2025-04-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofiletype_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user', 'type')},
        ),
    ]
