# Generated by Django 5.1.7 on 2025-05-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='ID subskrypcji Stripe użytkownika', max_length=255, null=True, verbose_name='ID subskrypcji Stripe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_active',
            field=models.BooleanField(default=False, help_text='Czy użytkownik ma aktywną subskrypcję', verbose_name='Czy aktywna subskrypcja'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('basic', 'Podstawowy'), ('tourist', 'Turysta'), ('guide', 'Przewodnik')], help_text='Plan subskrypcyjny użytkownika', max_length=50, null=True, verbose_name='Plan subskrypcyjny'),
        ),
    ]
