# Generated by Django 5.1.7 on 2025-05-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_plan',
        ),
    ]
