# Generated by Django 5.1.7 on 2025-05-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('free', 'Podstawowy'), ('tourist', 'Turysta'), ('guide', 'Przewodnik')], default='free', help_text='Plan subskrypcyjny użytkownika', max_length=50, null=True, verbose_name='Plan subskrypcyjny'),
        ),
    ]
