name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: HRKU-30b9dda9-e3de-445f-bbe5-09b15f48ca24
        run: |
          git remote add heroku "https://heroku:${HEROKU_API_KEY}@git.heroku.com/backend-plannder.git"
          git push heroku `git subtree split --prefix backend main`:main --force
      
      # - name: Deploy to Heroku
      #   run: |
      #     git remote add heroku https://git.heroku.com/backend-plannder.git
      #     git subtree push --prefix backend heroku main
      #   env:
      #     HEROKU_API_KEY: 
      #     HEROKU_EMAIL: s25668@pjwstk.edu.pl
