name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku "https://heroku:${HEROKU_API_KEY}@git.heroku.com/backend-plannder.git"
          git push heroku `git subtree split --prefix backend main`:main --force
      
      - name: Run Migrations on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku run python manage.py makemigrations --app backend-plannder
          heroku run python manage.py migrate --app backend-plannder
