name: Deploy Backend

on:
  push:
    branches: [ "slave" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/backend-plannder.git
          git subtree push --prefix backend heroku main
        env:
          HEROKU_API_KEY: HRKU-30b9dda9-e3de-445f-bbe5-09b15f48ca24
          HEROKU_EMAIL: s25668@pjwstk.edu.pl
